### ISSUE TITLE
icite command not working

### ISSUE THREAD

**Issue by aditya-sarkar441** [dvklopfenstein/pmidcite#1]
I installed the github repo and used the make command but icite command was not working. Can someone please help me with this ?

**Comment by dvklopfenstein** [comment]
Hello @aditya-sarkar441,

Thank you for your interest in pmidcite and taking the time to write me.

What error messages are you seeing? Can you copy and paste them in this issue?

How did you download pmidcite? Using github clone or pip install or some other method?

Thank you again for taking your time to write and open this issue.

**Comment by aditya-sarkar441** [comment]
@dvklopfenstein The cluster people resolved the issue. Actually I cloned this github repo and then compiled the make command. After that I tried to use icite -h command and it was showing command not found error. Since it has been resolved, I'm closing the issue. Thanks for your reply.
